# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS_View_Demos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS_View_Demos
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SnapKit', '~> 3.2.0'
  pod 'Kingfisher', '~> 3.9.0'
  pod 'KissXML', '~> 5.2.0'
  pod 'SwiftyJSON'
  pod 'LCActionSheet'


end

